### ISSUE TITLE
The URL to the backend changed

### ISSUE THREAD

**Issue by Weltraumschaf** [nickjj/title-case-converter#3]
First: Thanks for this handy script, I use it a lot.

It is broken with error:

```
Traceback (most recent call last):
  File "/Users/sst/bin/tcc", line 103, in <module>
    body_json = json.loads(body)[0]
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

The obvious part for me: The changed the backend URL used in the website's form from `https://titlecaseconverter.com/cgi-bin/tcc.pl` to `https://titlecaseconverter.com/tcc/`.

The request parameters seem to be unchanged. I tried the new URL, but I didn't get it worked. Due to lack of Python skills :(

**Comment by nickjj** [comment]
Hi,

Yep I noticed this change too.

Things drastically changed. They introduced a proper API now at https://titlecaseconverter.com/api/.

It will require a number of changes to this script to make it work. But it also involves signing up for RapidAPI to use the API, which requires a credit card even if you're under the free plan which is 100 calls or less per month.

In the mean time, you can convert your title manually at https://titlecaseconverter.com/. I don't know what implications that will be for your work flow, but it's a solution for today. I'd like to update this script to use their API tho, because I mainly use this script to integrate it into my editor.

**Comment by avanavana** [comment]
Ah I thought that's what might have happened :(

**Comment by lgrosz** [comment]
@nickjj, I am in the same boat, I have an editor that I find myself often entering titles and want this sort of "smart-title-casing" check. Have you migrated to something else in your own editor?

**Comment by nickjj** [comment]
I just use https://titlecaseconverter.com/ directly since I only fiddle with titles about once in a week.
